<?php

/**
 * @file Contains hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function diff_form_node_type_edit_form_alter(&$form, $form_state) {
  // @todo Follow this issue: https://www.drupal.org/node/1728788.
  $type = $form_state['controller']->getEntity();
  if ($type->id()) {
    $config = \Drupal::configFactory()->get('diff.settings');

    $form['diff'] = array(
      '#title' => t('Compare revisions'),
      '#type' => 'details',
      '#group' => 'additional_settings',
      '#tree' => FALSE,
    );

    $form['diff']['show_preview_changes'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show <em>View changes</em> button on node edit form'),
      '#default_value' => $config->get('content_type_settings.' . $type->id() . '.show_preview_changes'),
      '#weight' => 10,
    );

    $form['diff']['enable_revisions_page'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable the <em>Revisions</em> page for this content type'),
      '#default_value' => $config->get('content_type_settings.' . $type->id() . '.enable_revisions_page'),
      '#weight' => 11,
    );

    $options = array();
    // Get all view modes for node entity type.
    $node_view_modes = \Drupal::entityManager()->getViewModes('node');
    foreach ($node_view_modes as $view_mode => $view_mode_info) {
      $options[$view_mode] = $view_mode_info['label'];
    }

    $form['diff']['view_mode'] = array(
      '#type' => 'select',
      '#title' => t('Standard comparison preview'),
      '#description' => t('Governs the <em>Current revision</em> view mode when doing comparisons.'),
      '#options' => $options,
      '#weight' => 13,
      '#default_value' => $config->get('content_type_settings.' . $type->id() . '.view_mode'),
      '#empty_value' => '',
      '#empty_option' => t('- Do not display -'),
    );

    $form['actions']['submit']['#submit'][] = 'diff_form_node_type_form_submit';
  }
}

/**
 * Submit handler for forms with menu options.
 *
 * @see diff_form_node_type_edit_form_alter().
 */
function diff_form_node_type_form_submit(&$form, $form_state) {
  $type = $form_state['controller']->getEntity();
  \Drupal::config('diff.settings')
    ->set('content_type_settings.' . $type->id() . '.show_preview_changes', $form_state['values']['show_preview_changes'])
    ->set('content_type_settings.' . $type->id() . '.enable_revisions_page', $form_state['values']['enable_revisions_page'])
    ->set('content_type_settings.' . $type->id() . '.view_mode', $form_state['values']['view_mode'])
    ->save();
}

/**
 * Implements hook_help().
 */
function diff_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.diff':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Diff module replaces the normal <em>Revisions
        </em> node tab and enhances the listing of revisions with an option to
        view the differences between any two content revisions.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Compare content entity revisions') . '</dt>';
      $output .= '<dd>' . t('Diff provides the possibility of comparing two node
        revisions but it also provides support for comparing any two content
        entities. With minimum effort it can be extended to display differences
        between any two content entities.') . '</dd>';
      $output .= '<dt>' . t('Control field visibility settings') . '</dt>';
      $output .= '<dd>' . t('Fields visibility can be controlled from view modes
        for configurable fields and from Diff settings page for entity base
        fields. Diff field types specific settings can also be configured from
        Diff settings page') . '</dd>';
      $output .= '<dt>' . t('Configure diff field type settings') . '</dt>';
      $output .= '<dd>' . t('Every field type has specific diff settings
        (display or not the title of the field, markdown format, etc.). These
        settings can be configured from Diff settings page') . '</dd>';
      $output .= '</dl>';
      return $output;

    case 'diff.revisions_diff':
      return '<p>' . t('Comparing two revisions:') . '</p>';

    case 'diff.revision_overview':
      return '<p>' . t('Revisions allow you to track differences between multiple
      versions of your content, and revert back to older versions.') . '</p>';
  }
}
